defmodule Smurf.Repo.Migrations.ImageUrls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:themes) do
      add :image, :text
    end

    alter table(:codenames) do
      add :image, :text
    end
  end

  def down do
    alter table(:codenames) do
      remove :image
    end

    alter table(:themes) do
      remove :image
    end
  end
end